export const chameleons = [
  {
    id: 1,
    imageUrl: "panther-chameleons/1.png",
    title: "Хамелеон Пантеровый",
    desc: "Furcifer pardalis",
    price: 100000,
  },
  {
    id: 2,
    imageUrl: "panther-chameleons/2.png",
    title: "Хамелеон Крокодиловый",
    desc: "Furcifer Verrucosus",
    price: 370000,
  },
  {
    id: 3,
    imageUrl: "panther-chameleons/3.png",
    title: "Хамелеон Ambato",
    desc: "Furcifer pardalis",
    price: 150000,
  },
  {
    id: 4,
    imageUrl: "panther-chameleons/4.png",
    title: "Хамелеон Кампани самка",
    desc: "Furcifer pardalis",
    price: 70000,
  },
  {
    id: 5,
    imageUrl: "panther-chameleons/5.png",
    title: "Хамелеон Ковровый",
    desc: "Furcifer pardalis",
    price: 97000,
  },
  {
    id: 6,
    imageUrl: "panther-chameleons/6.png",
    title: "Хамелеон Tamatave",
    desc: "Furcifer Verrucosus",
    price: 57000,
  },
  {
    id: 7,
    imageUrl: "panther-chameleons/7.png",
    title: "Хамелеон Abanja Blue",
    desc: "Furcifer pardalis",
    price: 15000,
  },
  {
    id: 8,
    imageUrl: "panther-chameleons/8.png",
    title: "Хамелеон Парсона",
    desc: "Furcifer pardalis",
    price: 73000,
  },
  {
    id: 9,
    imageUrl: "panther-chameleons/9.png",
    title: "Хамелеон Антимена",
    desc: "Furcifer pardalis",
    price: 100000,
  },
  {
    id: 10,
    imageUrl: "panther-chameleons/10.png",
    title: "Хамелеон О'Шонесси",
    desc: "Furcifer Verrucosus",
    price: 37000,
  },
  {
    id: 11,
    imageUrl: "panther-chameleons/11.png",
    title: "Хамелеон Кампани",
    desc: "Furcifer pardalis",
    price: 150000,
  },
  {
    id: 12,
    imageUrl: "panther-chameleons/12.png",
    title: "Хамелеон Парсона самка",
    desc: "Furcifer pardalis",
    price: 170000,
  },
];
