export const spiders = [
  {
    id: 1,
    imageUrl: "spiders/1.png",
    title: "Птицеед Гигантский",
    desc: "Rhacodactylus Leachianus Henkeli",
    price: 6000,
  },
  {
    id: 2,
    imageUrl: "spiders/2.png",
    title: "Паук скакунчик",
    desc: "Crested Gecko",
    price: 8000,
  },
  {
    id: 3,
    imageUrl: "spiders/3.png",
    title: "Птицеед Реснитчатый Fire",
    desc: "Crested Gecko",
    price: 5000,
  },
  {
    id: 4,
    imageUrl: "spiders/4.png",
    title: "Паук скакунчик королевский",
    desc: "Rhacodactylus",
    price: 3000,
  },
  {
    id: 5,
    imageUrl: "spiders/5.png",
    title: "Птицеед Красноколенный",
    desc: "Crested Gecko",
    price: 3000,
  },
  {
    id: 6,
    imageUrl: "spiders/6.png",
    title: "Птицеед Реснитчатый Normal",
    desc: "Crested Gecko",
    price: 7000,
  },
  {
    id: 7,
    imageUrl: "spiders/7.png",
    title: "Птицеед Реснитчатый Small",
    desc: "Crested Gecko",
    price: 15000,
  },
];
